name: Playwright Test
on:
  push:
    branches: [ main ]
jobs:
  playwrighttests:
    runs-on: ubuntu-lastest
    steps: 
      - name: Checkout repository
        uses: action/chekout@v2
      - name: Say hello
        run: echo Hello