name: Playwright Test
on:
  push:
    branches: [ main ]
jobs:
  playwrighttests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.50.1-noble
      env:
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD}}
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2  
      - name: Run tests
        run: |
          echo "Strart the shopping store application"
          chmod +x ./shopping-store-linux-amd64 &
          echo "Install dependencies from lockfile"
          npm ci
          echo "Run playwright tests"
          npm run test:ci