name: Playwright Tests
on:
  push:
    branches: [ main ]
jobs:
  playwrighttests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.49.0-jammy
      env:
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Instalar dependencias
        run: npm ci

      - name: Verificar y detener cualquier proceso en puerto 2221
        run: |
          sudo lsof -i :2221 && sudo kill -9 $(sudo lsof -t -i:2221) || echo "No hay procesos en el puerto 2221"

      - name: Iniciar la aplicación de prueba
        run: |
          chmod +x ./shopping-store-linux-amd64
          nohup ./shopping-store-linux-amd64 > server.log 2>&1 &  # Ejecuta el servidor en segundo plano
          echo "Esperando a que el servidor esté listo..."
          sleep 20  # Espera 20 segundos antes de verificar

      - name: Verificar que el servidor está corriendo
        run: curl --retry 10 --retry-connrefused --retry-delay 5 -s http://localhost:2221 || exit 1

      - name: Ejecutar pruebas con Playwright
        run: npm run test:ci
