name: Playwright Tests
on:
  push:
    branches: [ main ]
jobs:
  playwrighttests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.49.0-jammy
      env:
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Stop existing server (if running)
        run: |
          echo "Deteniendo cualquier proceso en el puerto 2221..."
          fuser -k 2221/tcp || true
          pkill -f shopping-store-linux-amd64 || true
          echo "Verificando que el puerto 2221 está libre..."
          sleep 5  # Espera un momento para asegurarse de que el proceso se cerró

      - name: Start the shopping store application
        run: |
          chmod +x ./shopping-store-linux-amd64
          ./shopping-store-linux-amd64 &  # Inicia el servidor en segundo plano
          echo "Esperando a que el servidor esté listo..."
          sleep 15  # Espera 15 segundos antes de verificar
          echo "Verificando si el servidor responde..."
          curl --retry 10 --retry-connrefused --retry-delay 5 -s http://localhost:2221 || (echo "El servidor no se inició correctamente" && exit 1)

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        run: npm run test:ci