name: Playwright Tests
on:
  push:
    branches: [ main ]

jobs:
  playwrighttests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.49.0-jammy
      env:
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set execute permissions for the shopping store binary
        run: chmod +x ./shopping-store-linux-amd64

      - name: Start the shopping store application
        run: |
          ./shopping-store-linux-amd64 &
          echo "Esperando que el servidor esté activo..."
          until curl --output /dev/null --silent --head --fail http://localhost:2221; do
              echo "Servidor no disponible, esperando..."
              sleep 2
          done
          echo "Servidor activo en http://localhost:2221"

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        run: npm run test:ci